[project]
name = "support"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "gradio>=6.1.0",
    "openai-agents>=0.6.2",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "python-dotenv>=1.2.1",
    "structlog>=25.5.0",
]
